In [ ]:
import pandas as pd
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics import (
	accuracy_score,
	precision_score,
	recall_score,
	f1_score,
	roc_auc_score,
	roc_curve,
	auc,
	 brier_score_loss, confusion_matrix
)

from sklearn.utils import resample

In [ ]:
log_path = "NCV_4_3_folds/OUTERs_4_evaluating.txt"
columns = [ "ExpID", "HP_Set",  "Fold",   "CaseID" , "GroundTruth",  "prediction" ,  "probability"]
df = pd.read_csv(log_path, sep=r'\s*;\s*', engine='python')
print(df.columns)
df = df[columns]
df.columns = df.columns.str.strip()  # clean column names
for col in df.select_dtypes(['object']).columns:
	df[col] = df[col].str.strip()
df = df[columns]
#df.to_csv('data/NCV_history/OUTER_RESULTS.csv', index=False)        #DO I REALLY NEED IT IN CSV?
df

Index(['Time', 'ExpID', 'HP_Set', 'Fold', 'CaseID', 'GroundTruth',
       'prediction', 'probability', 'Unnamed: 8'],
      dtype='object')

,ExpID,HP_Set,Fold,CaseID,GroundTruth,prediction,probability
0,1,6,0,TTS_MDW_22867501_81F,True,True,0.7456
1,1,6,0,CNTRL_LLM_24775207_66F,False,False,0.3255
2,1,6,0,TTS_JL_4008074_71F,True,True,0.6380
3,1,6,0,CNTRL_NEA_10026953_70M,False,False,0.4058
4,1,6,0,TTS_MGR_2545663_93M,True,True,0.6166
...,...,...,...,...,...,...,...
274,8,9,3,CNTRL_DJM_50424301_78M,False,False,0.0816
275,8,9,3,TTS_BFM_10624765_79F,True,True,0.6691
276,8,9,3,TTS_WF_10497121_62F,True,True,0.8845
277,8,9,3,TTS_MC_3887643_88F,True,True,0.8473
278,8,9,3,CNTRL_AB_10470318_90F,False,True,0.6200

In [24]:
def confusion_derived(y_true, y_pred):
	tn, fp, fn, tp = confusion_matrix(y_true, y_pred).ravel()
	# Prediction-focused
	ppv = tp / (tp + fp) if (tp + fp) > 0 else 0.0  # Positive Predictive Value (Precision)
	npv = tn / (tn + fn) if (tn + fn) > 0 else 0.0  # Negative Predictive Value
	# Error rates
	fpr = fp / (fp + tn) if (fp + tn) > 0 else 0.0  # False Positive Rate = 1 - Specificity
	fnr = fn / (fn + tp) if (fn + tp) > 0 else 0.0  # False Negative Rate = 1 - Sensitivity
	# Sensitivity/Specificity for completeness
	sensitivity = tp / (tp + fn) if (tp + fn) > 0 else 0.0  # Recall / TPR
	specificity = tn / (tn + fp) if (tn + fp) > 0 else 0.0  # TNR
	return ppv, npv, fpr, fnr, sensitivity, specificity

In [25]:
#uncalibrated_brier, calibrated_brier,

fold_metrics = []
folds = sorted(df['Fold'].unique())
for fold_id in folds:
	fold_df = df[df['Fold'] == fold_id]

	y_true = fold_df['GroundTruth'].astype(int).values
	y_pred = fold_df['prediction'].astype(int).values
	y_prob = fold_df['probability'].astype(float).values

	ppv, npv, fpr, fnr, sensitivity, specificity = confusion_derived(y_true, y_pred)

	metrics = {
		'model': 'MultiViewCNN',
		'Fold': fold_id,
		'Accuracy': accuracy_score(y_true, y_pred),
		'Precision': precision_score(y_true, y_pred, zero_division=0),
		'Recall': recall_score(y_true, y_pred, zero_division=0),
		'F1-Score': f1_score(y_true, y_pred, zero_division=0),
		'AUC': roc_auc_score(y_true, y_prob),
		'Brier': brier_score_loss(y_true, y_prob),
		'PPV': ppv,
		'NPV': npv,
		'FPR': fpr,
		'FNR': fnr,
		'Sensitivity': sensitivity,
		'Specificity': specificity,
	}
	fold_metrics.append(metrics)

metrics_df = pd.DataFrame(fold_metrics)
metrics_df

,model,Fold,Accuracy,Precision,Recall,F1-Score,AUC,Brier,PPV,NPV,FPR,FNR,Sensitivity,Specificity
0,MultiViewCNN,0,0.913978,1.000000,0.833333,0.909091,0.979630,0.094080,1.000000,0.849057,0.000000,0.166667,0.833333,1.000000
1,MultiViewCNN,1,0.951613,0.967742,0.937500,0.952381,0.982292,0.065685,0.967742,0.935484,0.033333,0.062500,0.937500,0.966667
2,MultiViewCNN,2,0.919355,0.935484,0.906250,0.920635,0.980208,0.066672,0.935484,0.903226,0.066667,0.093750,0.906250,0.933333
3,MultiViewCNN,3,0.935484,0.941176,0.941176,0.941176,0.990546,0.061574,0.941176,0.928571,0.071429,0.058824,0.941176,0.928571

In [ ]:
summary = (metrics_df
           .drop(columns=['model','Fold'])
           .agg(['mean','std'])
           .T
           .sort_index())
summary

                 mean       std
AUC          0.983169  0.005049
Accuracy     0.930108  0.017001
Brier        0.072003  0.014883
F1-Score     0.930821  0.019562
FNR          0.095435  0.050006
FPR          0.042857  0.033220
NPV          0.904084  0.039219
PPV          0.961101  0.029498
Precision    0.961101  0.029498
Recall       0.904565  0.050006
Sensitivity  0.904565  0.050006
Specificity  0.957143  0.033220

In [ ]:
print(summary)

                 mean       std
AUC          0.983169  0.005049
Accuracy     0.930108  0.017001
Brier        0.072003  0.014883
F1-Score     0.930821  0.019562
FNR          0.095435  0.050006
FPR          0.042857  0.033220
NPV          0.904084  0.039219
PPV          0.961101  0.029498
Precision    0.961101  0.029498
Recall       0.904565  0.050006
Sensitivity  0.904565  0.050006
Specificity  0.957143  0.033220

In [ ]:
### only on final test set,, not folds

def bootstrap_ci(y_true, y_pred, y_prob=None, metric="accuracy", n_boot=5000, alpha=0.05):
	n = len(y_true)
	stats = []
	for _ in range(n_boot):
		idx = resample(np.arange(n), replace=True, n_samples=n)
		yt, yp = y_true[idx], y_pred[idx]
		if metric == "accuracy":
			stats.append(accuracy_score(yt, yp))
		elif metric == "precision":
			stats.append(precision_score(yt, yp, zero_division=0))
		elif metric == "recall":
			stats.append(recall_score(yt, yp, zero_division=0))
		elif metric == "f1":
			stats.append(f1_score(yt, yp, zero_division=0))
		elif metric == "auc" and y_prob is not None:
			if len(np.unique(yt)) > 1:  # AUC requires both classes present
				stats.append(roc_auc_score(yt, y_prob[idx]))
		elif metric == "brier" and y_prob is not None:
			stats.append(brier_score_loss(yt, y_prob[idx]))
	stats = np.array(stats)
	mean = np.nanmean(stats)
	low = np.nanpercentile(stats, 100*alpha/2)
	high = np.nanpercentile(stats, 100*(1-alpha/2))
	return mean, (low, high)

In [ ]:
y_true = df["GroundTruth"].astype(int).values
y_pred = df["prediction"].astype(int).values
y_prob = df["probability"].astype(float).values
for m in ["accuracy", "precision", "recall", "f1", "auc", "brier"]:
	mean, (low, high) = bootstrap_ci(y_true, y_pred, y_prob, metric=m)
	print(f"{m.capitalize()}: {mean:.3f} (95% CI {low:.3f}–{high:.3f})")

Accuracy: 0.929 (95% CI 0.896–0.957)
Precision: 0.964 (95% CI 0.930–0.993)
Recall: 0.898 (95% CI 0.848–0.944)
F1: 0.929 (95% CI 0.896–0.958)
Auc: 0.982 (95% CI 0.967–0.993)
Brier: 0.074 (95% CI 0.062–0.087)

In [ ]:
import json


# Define the parameter grids for each benchmark model
MLP_PARAM_GRID = [
	{"paramID": 101, "LR": 0.001,  "WD": 1e-5, "DR": 0.4},
	#{"paramID": 102, "LR": 0.0005, "WD": 1e-4, "DR": 0.4},
	#{"paramID": 103, "LR": 0.005,  "WD": 1e-6, "DR": 0.4},
]

SINGLEVIEW_PARAM_GRID = [
	#{"paramID": 203, "LR": 0.0003, "WD": 1e-4, "DR": 0.3},
	{"paramID": 201, "LR": 0.0005, "WD": 1e-5, "DR": 0.4},
	#{"paramID": 202, "LR": 0.0007, "WD": 1e-6, "DR": 0.2},
]

RESNET_PARAM_GRID = [
	#{"paramID": 303, "LR": 0.0005, "WD": 1e-4, "DR": 0.6},
	{"paramID": 301, "LR": 0.001,  "WD": 1e-5, "DR": 0.5},
	#{"paramID": 302, "LR": 0.005,  "WD": 1e-5, "DR": 0.4},
]

# --- Main script to generate the JSON file ---
all_experiments = []
experiment_id_counter = 1
num_outer_folds = 4
#num_inner_folds = 3
epochs =  50
threshold = 0.5

# 1. Add experiments for MetadataMLP
for params in MLP_PARAM_GRID:
	for fold_id in range(num_outer_folds):
		experiment = {
			"Model": "MLP_META",
			"ExpID": experiment_id_counter,
			"OUTER_FOLD": fold_id,
			#"INNER_FOLD": 0,
			"hypers": {
				"HPset": params["paramID"],
				"LR": params["LR"],
				"WD": params["WD"],
				"DR": params["DR"],
				"TH": threshold,
				"P": 5,
				"epochs": epochs,
			},
			"trained": False,
			"evaluated": False
		}
		all_experiments.append(experiment)
		experiment_id_counter += 1

# 2. Add experiments for SingleViewClassifier (for each view)
for view in ["Axial", "Sagittal", "Coronal"]:
	for params in SINGLEVIEW_PARAM_GRID:
		for fold_id in range(num_outer_folds):
			experiment = {
				"Model": f"SingleView_{view}",
				"ExpID": experiment_id_counter,
				"OUTER_FOLD": fold_id,
				#"INNER_FOLD": 0,
				"hypers": {
					"HPset": params["paramID"],
					"LR": params["LR"],
					"WD": params["WD"],
					"DR": params["DR"],
					"TH": threshold,
					"P": 5,
					"epochs": epochs,
				},
				"trained": False,
				"evaluated": False
			}
			all_experiments.append(experiment)
			experiment_id_counter += 1

# 3. Add experiments for ResNet-18

for params in RESNET_PARAM_GRID:
	for fold_id in range(num_outer_folds):
		experiment = {
			"Model": f"ResNet18",
			"ExpID": experiment_id_counter,
			"OUTER_FOLD": fold_id,
			#"INNER_FOLD": 0,
			"hypers": {
				"HPset": params["paramID"],
				"LR": params["LR"],
				"WD": params["WD"],
				"DR": params["DR"],
				"TH": threshold,
				"P": 5,
				"epochs": epochs,
			},
			"trained": False,
			"evaluated": False
		}
		all_experiments.append(experiment)
		experiment_id_counter += 1

# Save the complete list of experiments to a JSON file
with open("NCV_4_3_folds/benchmark_experiments.json", "w") as f:
	json.dump(all_experiments, f, indent=2)